name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '**/docker-compose.yml'
      - '.github/workflows/docker-build-push.yml'

jobs:
  build-and-push:
    runs-on: [self-hosted, linux, worker1]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bpq-server:latest
